---
 - name: Run Flask Application
   hosts: webservers
   remote_user: root
   become: True
   become_method: sudo
   vars_files:
     - vars.yml
   tasks:
   - name: "Remove Old Files"
     command: rm -rf /var/www/flask
   - name: Create Directory
     command: mkdir /var/www/flask
   - name: Copy New Files
     command: cp -r /var/lib/jenkins/workspace/Ansible_test/ /var/www/flask
   - name: "Run Flask Server"
     shell: "(cd /var/www/flask/Ansible_test python __init__.py > log.txt 2>&1 &)"
     async: 10
     poll: 0
