---
 - name: Run Flask Application
   hosts: webservers
   remote_user: root
   become: True
   become_method: sudo
   vars_files:
     - vars.yml
   tasks:
   - name: "Copy Flask Files"
     command: {{ item }}
     with_items:
     - rm -rf /var/www/flask
     - mkdir /var/www/flask
     - cp ./* /var/www/flask
     command: "rm -rf /var/www/flask && mkdir /var/www/flask && cp ./* /var/www/flask && ls -l /var/www/flask"
   - name: "Run Flask Server"
     command: chdir=/var/www/flask python __init__.py
