---
 - name: Run Flask Application
   hosts: all
   remote_user: root
   vars_files:
     - vars.yml
   - name: Copy Flask Files
     template:
       src: ./*
       dest: /var/www/flask
   - name: Run Flask Server
     command: cd /var/www/flask && python __init__.py
