---
 - name: Run Flask Application
   hosts: webservers
   remote_user: root
   become: True
   become_method: sudo
   vars_files:
     - vars.yml
   tasks:
   - name: "Copy Flask Files"
     template:
       src: ./*
       dest: /var/www/flask
   - name: "Run Flask Server"
     command: cd /var/www/flask && python __init__.py
